FROM registry.suse.com/bci/golang:1.24

ARG DAPPER_HOST_ARCH
ENV HOST_ARCH ${DAPPER_HOST_ARCH} ARCH ${DAPPER_HOST_ARCH}

RUN zypper -n install git docker wget curl vim less file awk jq

ENV DAPPER_ENV REPO TAG OAUTH_TOKEN
ENV DAPPER_SOURCE /go/src/github.com/cnrancher/rancher-upgrade-authtool/
ENV DAPPER_OUTPUT ./bin ./dist
ENV DAPPER_DOCKER_SOCKET true
ENV GOCACHE /root/.cache/go-build
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
