#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo "VERSION=${VERSION}"
echo "COMMIT=${COMMIT}"

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
  LINKFLAGS="-extldflags -static -s"
fi

if [ "$OAUTH_TOKEN" != "" ]; then
   git config --global url."https://${OAUTH_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
fi

GOPRIVATE="github.com/cnrancher" CGO_ENABLED=0 GOPRIVATE="github.com/cnrancher" go build -tags k8s \
  -ldflags \
  "-X main.Version=$VERSION
   -X main.GitCommit=$COMMIT $LINKFLAGS" \
  -o bin/authtool main.go