#!/bin/bash

DIRTY=
if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=${COMMIT:-$(git rev-parse --short HEAD)}
GIT_TAG=${GIT_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="0.0.0-${COMMIT}${DIRTY}"
fi

if [ -z "${ARCH:-}" ] ; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"
TAG="${TAG:-${VERSION}${SUFFIX}}"
REPO="${REPO:-cnrancher}"

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

echo "ARCH: $ARCH"
echo "TAG: $TAG"
echo "VERSION: $VERSION"
